name: Auto-Deploy-Child-Runners

on:

  workflow_dispatch:
  
  workflow_call:
    inputs:
      main-runner-tag:
        required: true
        type: string

jobs:
  Deploy-Runners:
    runs-on: ubuntu-latest
    
    steps:

      - name: Starting Control-Node
        shell: sh
        run: |
           echo ${{inputs.main-runner-tag}}
           echo $GITHUB_WORKSPACE
           git version
           lsb_release -a
           #dt github install-runner --group=flex-dev --name=runner-003 --location=/home/thineshs/action-runner2/ephemeral-run/ --ldap-username=thineshs --ldap-password="${{secrets.TEST_SCRT}}" --label="child-runner" --ldap-domain=GAR --count=2 --no-prompt --no-start
           #RUNNER_TRACKING_ID="" && nohup /home/thineshs/action-runner2/ephemeral-run/intel/002/run.sh </dev/null &>/dev/null &
           #echo $RUNNER_TRACKING_ID
           #jobs -l      
           
  build:
    # The type of runner that the job will run on
    needs: Deploy-Runners
    runs-on: [child-runner]
    defaults:
      run:
        working-directory: .
    
    steps:

      - name: Starting Control-Node
        shell: sh
        run: |
           jobs -l
           echo $GITHUB_WORKSPACE
           echo "this is running from child node"
           
     
  removing-child-runners:
    needs: [Deploy-Runners, build]
    runs-on: [linux-ubuntu-test]
    defaults:
      run:
        working-directory: .
    
    steps:

      - name: Removing all child runner and proccess
        shell: sh
        run: |
           echo "Removing the child runners"
           rm -rf /home/thineshs/action-runner2/ephemeral-run/*
           ls /home/thineshs/action-runner2/ephemeral-run/
