name: CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo runnning from libraries
